from downloaders.soundcloud import download_soundcloud_mp3
from downloaders.youtube import yt_download_send_mp3
from downloaders.yamusic import download_yandex_music
from downloaders.compas import compas